app:
  name: ths-proxy
  log-level: info
  http:
    port: 8080
gics:
  base-url:
notification:
  match-service: addConsent
  email:
    recipients:
      info:
      debug:
    sender:
    smtp:
      server:
      port:
      user:
      password:
      helo: