name: build & test

on:
  push:
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 10m
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: build
        run: go build -v ./...
      - name: test
        run: go test -gcflags=-l -v  -coverprofile=coverage.txt -covermode=atomic ./...

      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
